/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-122792-g059c57a83e-20260219"
#endif /* AVUTIL_FFVERSION_H */
